### PR TITLE
Additional splitter tests

### PR DESCRIPTION
**Pull request by ghalliday**

### CODE REVIEW

**Comment by ghalliday** [comment]
@AttilaVamos are we routinely running these still?

**Comment by AttilaVamos** [comment]
@ghalliday Not in the last couple of years, based on we only have OpenStack based VMs and the results show significant variance run-by-run. 

Should I try it again in AKS/AWS?

**Review by AttilaVamos — APPROVED** [review]
Seems good for regression test engine/automated testing point of view.
(Do we want to keep as secret those magical heapOtions values?)

**Comment by ghalliday** [comment]
No need to keep the heap options secret

**Pull request merged**
